# Generated by Django 4.0.3 on 2022-06-13 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id_user', models.AutoField(primary_key=True, serialize=False)),
                ('last_name', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('domaine', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='sondage',
            fields=[
                ('id_sondage', models.AutoField(primary_key=True, serialize=False)),
                ('titre_sondage', models.CharField(max_length=100)),
                ('logo', models.ImageField(upload_to='')),
                ('url_sondage', models.URLField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user')),
            ],
        ),
    ]
