# Generated by Django 4.0.3 on 2022-07-02 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_admin_password_admin_remove_admin_username_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Modele_personnalisable',
            fields=[
                ('sondage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.sondage')),
            ],
            bases=('api.sondage',),
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_theme', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='page',
            name='fk_sondage1',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='api.sondage'),
        ),
        migrations.AddField(
            model_name='question',
            name='fk_page',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='api.page'),
        ),
        migrations.CreateModel(
            name='Question_predefinie',
            fields=[
                ('question_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.question')),
                ('fk_modele_personnalisable', models.ManyToManyField(to='api.modele_personnalisable')),
                ('fk_theme1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.theme')),
            ],
            bases=('api.question',),
        ),
        migrations.AddField(
            model_name='modele_personnalisable',
            name='fk_theme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.theme'),
        ),
    ]
