# Generated by Django 4.0.3 on 2022-07-02 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_parametre_option_reponse'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_page', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intitule_question', models.CharField(max_length=300)),
                ('obligatoire', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Repondant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_repondant', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Reponse_enquete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heure_debut', models.TimeField(max_length=300)),
                ('heure_fin', models.TimeField(max_length=300)),
                ('date', models.DateField(max_length=300)),
                ('fk_repondant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.repondant')),
                ('fk_sondage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.sondage')),
            ],
        ),
    ]
