# Generated by Django 4.0.3 on 2022-07-02 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_admin_reponse'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admin',
            name='password_admin',
        ),
        migrations.RemoveField(
            model_name='admin',
            name='username',
        ),
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default='', max_length=100),
        ),
    ]
