# Generated by Django 4.0.7 on 2022-09-11 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_rename_fk_question_reponse_c_alter_sondage_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sondage',
            name='logo',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
